
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.text.StyledDocument;
import javax.swing.text.rtf.RTFEditorKit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ROOT
 */
public class Menu1 extends javax.swing.JFrame {

    private JPopupMenu popup;

    /**
     * Creates new form Menu1
     */
    public Menu1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtpTextos = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        menuFrases = new javax.swing.JMenu();
        mnuFrase1 = new javax.swing.JMenuItem();
        mnuFrase2 = new javax.swing.JMenuItem();
        mnuFrase3 = new javax.swing.JMenuItem();
        mnuFrase4 = new javax.swing.JMenuItem();
        mnuFrase5 = new javax.swing.JMenuItem();
        menuCanciones = new javax.swing.JMenu();
        mnuCancion1 = new javax.swing.JMenuItem();
        mnuCancion2 = new javax.swing.JMenuItem();
        mnuCancion3 = new javax.swing.JMenuItem();
        mnuCancion4 = new javax.swing.JMenuItem();
        mnuCancion5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuGuardar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtpTextos);

        jMenuPrincipal.setText("Principal");

        menuFrases.setText("Frases");

        mnuFrase1.setText("Frase1");
        mnuFrase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFrase1ActionPerformed(evt);
            }
        });
        menuFrases.add(mnuFrase1);

        mnuFrase2.setText("Frase2");
        mnuFrase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFrase2ActionPerformed(evt);
            }
        });
        menuFrases.add(mnuFrase2);

        mnuFrase3.setText("Frase3");
        mnuFrase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFrase3ActionPerformed(evt);
            }
        });
        menuFrases.add(mnuFrase3);

        mnuFrase4.setText("Frase4");
        mnuFrase4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFrase4ActionPerformed(evt);
            }
        });
        menuFrases.add(mnuFrase4);

        mnuFrase5.setText("Frase5");
        mnuFrase5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFrase5ActionPerformed(evt);
            }
        });
        menuFrases.add(mnuFrase5);

        jMenuPrincipal.add(menuFrases);

        menuCanciones.setText("Canciones");
        menuCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancionesActionPerformed(evt);
            }
        });

        mnuCancion1.setText("Cancion1");
        menuCanciones.add(mnuCancion1);

        mnuCancion2.setText("Cancion2");
        mnuCancion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCancion2ActionPerformed(evt);
            }
        });
        menuCanciones.add(mnuCancion2);

        mnuCancion3.setText("Cancion3");
        mnuCancion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCancion3ActionPerformed(evt);
            }
        });
        menuCanciones.add(mnuCancion3);

        mnuCancion4.setText("Cancion4");
        menuCanciones.add(mnuCancion4);

        mnuCancion5.setText("Cancion5");
        menuCanciones.add(mnuCancion5);

        jMenuPrincipal.add(menuCanciones);

        jMenuBar1.add(jMenuPrincipal);

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        menuGuardar.setText("Guardar");
        menuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(menuGuardar);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCancion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCancion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCancion2ActionPerformed

    private void mnuCancion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCancion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCancion3ActionPerformed

    private void mnuFrase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFrase1ActionPerformed
        // TODO add your handling code here:
        txtpTextos.setText("Hola mundo \n Cruel");
    }//GEN-LAST:event_mnuFrase1ActionPerformed

    private void mnuFrase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFrase3ActionPerformed
        // TODO add your handling code here:
        txtpTextos.setText("huele a obo \n ¿Que es Obo? \n ESTA");
    }//GEN-LAST:event_mnuFrase3ActionPerformed

    private void mnuFrase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFrase2ActionPerformed
        // TODO add your handling code here:
        txtpTextos.setText("Una frase \n refrigerador");
    }//GEN-LAST:event_mnuFrase2ActionPerformed

    private void mnuFrase4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFrase4ActionPerformed
        // TODO add your handling code here:
        txtpTextos.setText("Si un gato muere puierde una vida? O perdio todas?");
    }//GEN-LAST:event_mnuFrase4ActionPerformed

    private void mnuFrase5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFrase5ActionPerformed
        // TODO add your handling code here:
        txtpTextos.setText("Tengo mucha tarea, no se que hago aqui");
    }//GEN-LAST:event_mnuFrase5ActionPerformed

    private void menuCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCancionesActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        // TODO add your handling code here:
        String nombreArchivo = "";
        JFileChooser manejador = new JFileChooser();
        manejador.showSaveDialog(this);
        nombreArchivo = manejador.getSelectedFile().getAbsolutePath();
        BufferedOutputStream salidaDatos;
        
        try{
            StyledDocument doc = (StyledDocument) txtpTextos.getDocument();
            RTFEditorKit kit = new RTFEditorKit();
            salidaDatos = new BufferedOutputStream(new FileOutputStream(nombreArchivo));
            kit.write(salidaDatos, doc, doc.getStartPosition().getOffset(), doc.getLength());
            salidaDatos.write('a');
            salidaDatos.flush();
            salidaDatos.close();
        }catch(Exception error){
            System.out.println("Ocurrio un error: " + error.toString());
            JOptionPane.showMessageDialog(this, "Ocurrio un error: " + error.toString());
        }
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        popup = new JPopupMenu();
popup.add(new AccionMenu("uno"));
popup.add(new AccionMenu("dos"));
popup.add(new AccionMenu("tres"));
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuCanciones;
    private javax.swing.JMenu menuFrases;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem mnuCancion1;
    private javax.swing.JMenuItem mnuCancion2;
    private javax.swing.JMenuItem mnuCancion3;
    private javax.swing.JMenuItem mnuCancion4;
    private javax.swing.JMenuItem mnuCancion5;
    private javax.swing.JMenuItem mnuFrase1;
    private javax.swing.JMenuItem mnuFrase2;
    private javax.swing.JMenuItem mnuFrase3;
    private javax.swing.JMenuItem mnuFrase4;
    private javax.swing.JMenuItem mnuFrase5;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTextPane txtpTextos;
    // End of variables declaration//GEN-END:variables
}
